name: taki
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_database: ^10.5.5
  cloud_firestore: ^4.17.2
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_colorpicker: ^0.5.0
  flutter_pdfview: ^1.3.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  page_transition: ^2.0.5
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/resimler/
    - assets/fileread/sangold1.pdf

