name: taki
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_database: ^10.5.5
  cloud_firestore: ^4.17.2
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_colorpicker: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - resimler/hotel.png
    - resimler/taki1.jpeg
    - resimler/taki2.jpeg
    - resimler/taki3.jpeg
    - resimler/taki4.jpeg
    - resimler/logo.jpeg
    - resimler/hyvnmodel0.png
    - resimler/hyvnmodel1.png
    - resimler/hyvnmodel2.png
    - resimler/slhmodel.png
    - resimler/hcmodel.png
    - resimler/slhmodel2.png
    - resimler/dnzmodel.png


