// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFP8J5JnwkL4l-l6DXjQof9sw9dPcWRsc',
    appId: '1:901068375184:web:08c9fa450008bcfdd88415',
    messagingSenderId: '901068375184',
    projectId: 'takiuygulamasi',
    authDomain: 'takiuygulamasi.firebaseapp.com',
    databaseURL: 'https://takiuygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'takiuygulamasi.appspot.com',
    measurementId: 'G-KMDBT3KRH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7_UMyTrExoSjZBjeWCLAgqqM05ewo3k',
    appId: '1:901068375184:android:49b7824935c50ee0d88415',
    messagingSenderId: '901068375184',
    projectId: 'takiuygulamasi',
    databaseURL: 'https://takiuygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'takiuygulamasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0uTFMFV6auALJW9T2HQIq7GNURjQ2xYc',
    appId: '1:901068375184:ios:e313e6761659a6d8d88415',
    messagingSenderId: '901068375184',
    projectId: 'takiuygulamasi',
    databaseURL: 'https://takiuygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'takiuygulamasi.appspot.com',
    iosBundleId: 'com.example.taki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0uTFMFV6auALJW9T2HQIq7GNURjQ2xYc',
    appId: '1:901068375184:ios:e313e6761659a6d8d88415',
    messagingSenderId: '901068375184',
    projectId: 'takiuygulamasi',
    databaseURL: 'https://takiuygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'takiuygulamasi.appspot.com',
    iosBundleId: 'com.example.taki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFP8J5JnwkL4l-l6DXjQof9sw9dPcWRsc',
    appId: '1:901068375184:web:856a16b21c09ae30d88415',
    messagingSenderId: '901068375184',
    projectId: 'takiuygulamasi',
    authDomain: 'takiuygulamasi.firebaseapp.com',
    databaseURL: 'https://takiuygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'takiuygulamasi.appspot.com',
    measurementId: 'G-YE9V66ETH2',
  );

}